#!/bin/bash

# 1.0 - Wed 18 Nov 2020 09:42:50 PM CET - first version

usage () {
	echo ""
    	echo "           Unified Kernel Manager "
    	echo "============================================"
    	echo ""
	echo "Usage: manage-unikernel [-v] [-h] [-i|-r]"
	echo ""
	echo "Options:"	
	echo -e "-v | --verbose \t\t Be verbose"
	echo -e "-h | --help \t\t This message"
	echo -e "-i | --install-hook \t Install the unikernel management scripts"
    	echo -e "-r | --remove-hook \t Remove the unikernel management scripts"
	echo ""
}

# is root?
if [ "$EUID" != "0" ]; then
	echo "Root privilege is required"
	exit 1
fi

# number of arguments required
if [ "$#" -lt "1" ]; then
	usage
	exit 1
fi

# global variables
verbose=""
install=""
install_dir="/usr/local/sbin"
kernel_in_exec=$(uname -r)
cmdline_in_exec=$(cat /proc/cmdline | head -1)

# prerequisites
(apt list efibootmgr | grep installed  > /dev/null) && (apt list binutils | grep installed  > /dev/null)
if [ "$?" != "0" ]; then
	echo "Error: the efibootmgr and binutils packages are required, please install it"
	exit 1
fi

# command switch parser
while [ "$1" != "" ]
do
	case "$1" in
		-h|--help)
    			usage
    			shift 1
    			;;
		-v|--verbose)
			verbose="--verbose"
			shift 1
			;;
		-i|--install-hook)
			install="Y"
			shift 1
			;;
		-r|--remove-hook)
			install="N"
			shift 1
			;;	
		-*|--*)
			echo "Error: unsupported argument $1"
			exit 1
	    		;;
		*)
			echo "Error: unrecognized argument $1"
			exit 1
	esac
done

case "$install" in
    Y)
	cp $verbose manage-unikernel delete-unikernel update-unikernel $install_dir
	chmod $verbose 755 $install_dir/manage-unikernel $install_dir/delete-unikernel $install_dir/update-unikernel
	mkdir $verbose --parents /etc/initramfs/post-update.d/		    		
	ln $verbose -s $install_dir/update-unikernel /etc/initramfs/post-update.d/99_update-unikernel
	ln $verbose -s $install_dir/delete-unikernel /etc/kernel/postrm.d/99_delete-unikernel			
	$install_dir/update-unikernel $verbose --cmdline "$cmdline_in_exec" "$kernel_in_exec" 
	exit 0
	;;
    N)
	echo "Do you want to remove ALL unikernels from boot directory and EFI boot manager?"
	echo "An alternative boot manager is required."
	echo "[Yy|Nn]"
	read answer	
	case "$answer" in
		Y|y)
			echo "Deleting all unikernels"
			$install_dir/delete-unikernel $verbose --all
			;;
		n|N|*)
			echo "Skipping deleting unikernels, you need to delete manually"
		esac
	rm $verbose /etc/kernel/postrm.d/99_delete-unikernel
	rm $verbose /etc/initramfs/post-update.d/99_update-unikernel
	rm $verbose $install_dir/update-unikernel $install_dir/delete-unikernel $install_dir/manage-unikernel
	exit 0
	;;
    *)
	echo "Warning: -i or -r argument is necessary to take any action"
	exit 1
esac

exit 0
#end